require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks! :linkage => :static

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)

  disable_capacitor_xcode16_issues = lambda do |build_settings|
    build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
    build_settings['ENABLE_MODULE_VERIFIER'] = 'NO'
    build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each { |config| disable_capacitor_xcode16_issues.call(config.build_settings) }
  end

  installer.pods_project.build_configurations.each do |config|
    disable_capacitor_xcode16_issues.call(config.build_settings)
  end

  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.native_targets.each do |target|
      target.build_configurations.each do |config|
        disable_capacitor_xcode16_issues.call(config.build_settings)
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end
    aggregate_target.user_project.build_configurations.each do |config|
      disable_capacitor_xcode16_issues.call(config.build_settings)
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
    aggregate_target.user_project.save
  end

  installer.pods_project.save
end
